/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mercadoTest;

public class App {

   

    public static void main(String[] args) {
        Estoque pro = new Estoque();
        pro.adicionarProduto("Ovo", 7);
pro.adicionarProduto("Ovo", 7);
   pro.adicionarProduto("pao", 7);
pro.produtoMaisEstocado();
    }
}
