/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mercadoTest;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {


    @Test
    public void testAdicionarProduto() {
        Estoque estoque = new Estoque();
        estoque.adicionarProduto("Produto A", 50);
        estoque.adicionarProduto("Produto A", 20);

        assertEquals(70, estoque.pp.get(0).getq());
    }

    @Test
    public void testRemoverProduto() {
        Estoque estoque = new Estoque();
        estoque.adicionarProduto("Produto B", 50);
        estoque.removerProduto("Produto B", 30);

        assertEquals(20, estoque.pp.get(0).getq());
    }

    @Test
    public void testConsultarQuantidade() {
        Estoque estoque = new Estoque();
        estoque.adicionarProduto("Produto C", 100);

        estoque.consultarQuantidade("Produto C");
    }

    @Test
    public void testProdutoMaisEstocado() {
        Estoque estoque = new Estoque();
        estoque.adicionarProduto("Produto A", 50);
        estoque.adicionarProduto("Produto B", 100);
        estoque.adicionarProduto("Produto C", 30);

        estoque.produtoMaisEstocado();
    }

    @Test
    public void testLimparEstoque() {
        Estoque estoque = new Estoque();
        estoque.adicionarProduto("Produto D", 10);
        estoque.limparEstoque();

        assertTrue(estoque.pp.isEmpty());
    }

    @Test
    public void testTem() {
        Estoque estoque = new Estoque();
        estoque.adicionarProduto("Produto E", 5);

        assertTrue(estoque.tem("Produto E"));
        assertFalse(estoque.tem("Produto F"));
    }
}
